### ISSUE TITLE
wifi wachtwoord

### ISSUE THREAD

**Issue by draxaris1010** [ZeusWPI/LEDDY#2]
https://github.com/ZeusWPI/LEDDY/blob/b6f46ebcef118a8ecde35891f32b39f3b498c087/servy/boot.py#L18

**Comment by redfast00** [comment]
Niet ideaal, maar ook geen ramp, we geven dat wachtwoord als mensen in de kelder komen. Hoe zou je dat fixen?

**Comment by redfast00** [comment]
(Zie ook de responsible disclosure policy op https://zeus.gent/.well-known/security.txt)
